version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/App.Dockerfile
    container_name: app
    working_dir: /var/www/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: soccerManagerDb-temp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRESQL_ROOT_USER: postgres
      POSTGRESQL_PASSWORD: postgres
    volumes:
      - ./:/var/www/app:cached
      - /var/www/app/node_modules # anonymous volume for node_modules only
    restart: always
    ports:
      - 3000:3000
    links:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: soccerManagerDb-temp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRESQL_ROOT_USER: postgres
      POSTGRESQL_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    # command: psql
    # command: CREATE DATABASE soccerManagerDb-temp OWNER postgres

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
